### ISSUE TITLE
Implement Fagin's rank aggregation methods

### ISSUE THREAD

**Issue by searchivarius** [searchivarius/NonMetricSpaceLib#32]
Efficient similarity search and classification via rank aggregation
R Fagin, R Kumar, D Sivakumar - Proceedings of the 2003 ACM …, 2003 - dl.acm.org

It's also patented:

Efficient similarity search and classification via rank aggregation
United States Patent Application 20040249831 Kind Code: A1

**Comment by aponom84** [comment]
úÁÂÁ×ÎÏ. ÷Ó£ ÐÁÔÅÎÔÕÀÔ )

**Comment by searchivarius** [comment]
Some working version https://github.com/searchivarius/NonMetricSpaceLib/commit/64e6910dfaa6c3b4a398faaac879415a732b79b1

**Comment by searchivarius** [comment]
Actually, for L2, I would need to implement LSH-like projections.
