### ISSUE TITLE
Can't compile on Ubuntu 12.04

### ISSUE THREAD

**Issue by erikbern** [searchivarius/NonMetricSpaceLib#54]
I keep getting this issue:
```
g++ -c -fpic -Wall -I/usr/include/python2.7 -I../similarity_search/include -std=c++11 -Ofast -fno-strict-aliasing nmslib.cc -o nmslib.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [nmslib.o] Error 1
g++ -c -fpic -Wall -I/usr/include/python2.7 -I../similarity_search/include -std=c++11 -Ofast -fno-strict-aliasing nmslib.cc -o nmslib.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [nmslib.o] Error 1
```

This is with the following environment variables:
```
export CXX="g++-4.8" CC="gcc-4.8"
export CMAKE_C_COMPILER=$CC
export CMAKE_CXX_COMPILER=$CXX
export CMAKE_C_COMPILER_ENV_VAR=CC
export CMAKE_CXX_COMPILER_ENV_VAR=CXX
```

It seems like the makefile doesn't respect the environment variables so I can't override the default ones (Ubuntu 12.04 defaults to GCC 4.6)

**Comment by erikbern** [comment]
Realized this is specifically for python bindings. I also figured out I can build them using "make CC=$CC" as a workaround so this might not be a huge issue

**Comment by erikbern** [comment]
https://github.com/erikbern/ann-benchmarks/blob/master/install/nmslib.sh#L18

**Comment by searchivarius** [comment]
This is not right, there is a mistake in the Makefile.

**Comment by searchivarius** [comment]
Now seems to be working with both
```
export CXX=
```
and
```
make CXX=g++-4.9
```

**Comment by erikbern** [comment]
Cool thanks

**Comment by searchivarius** [comment]
Please, note that make CC=... won't work any more. Sorry, it was some typo and CXX-variable in the makefile becamse CC.
